### ISSUE TITLE
Focus trap issue on react-aria-modal

### ISSUE THREAD

**Issue by adrianha** [davidtheclark/react-aria-modal#11]
Hi David,
I am facing an issue for focus trap when i implemented react-aria-modal into my project.
i got this: 

> Uncaught Error: You can't have a focus-trap without at least one focusable element

What cause the error?

**Comment by davidtheclark** [comment]
It means that there are no focusable elements inside your modal. There needs to be at least one to trap the focus. Or else you could use the [focusDialog](https://github.com/davidtheclark/react-aria-modal#focusdialog) prop to make the dialog itself receive focus.

Please let me know if that works for you. And then let's try to clear up the docs so this confusion doesn't strike others — any suggestions?

**Comment by adrianha** [comment]
You're right, It works to resolve the error. Maybe you can add the documentation about this. But the modal just showed the overlay, content inside its modal is not showed. i also have included required css. Any idea?

**Comment by davidtheclark** [comment]
> i also have included required css

I suspect it's a CSS problem, but I can't tell more without details. I'd say closely compare what you have to the demos and see what's different.

**Comment by adrianha** [comment]
okay @davidtheclark, thank you for your guidance. hope i can solve this issue. Btw, i really like your project (modal, tabpanel) 💃

**Comment by davidtheclark** [comment]
Feel free to re-open if you can't figure it out.
