### ISSUE TITLE
Console error in Firefox after switching tab while dialog is open

### ISSUE THREAD

**Issue by esseb** [davidtheclark/react-aria-modal#17]
Steps to reproduce:
1. Clone the repo and run `npm install` and `npm run demo-dev`
2. Open http://127.0.0.1:8080/ in Firefox
3. Make sure you have at least one other tab open in Firefox
4. Open Firefox's Developer Tools in the react-aria-modal demo tab
5. Open the first demo dialog
6. While the react aria modal dialog is open, switch to another tab in Firefox
7. Switch back to the react-aria-modal demo tab

Result:
`TypeError: e.target.blur is not a function`

Screenshot:
![screen shot 2016-08-24 at 16 47 43](https://cloud.githubusercontent.com/assets/207794/17935141/86ab9328-6a1a-11e6-8981-e13b0a878060.png)

Further information:
- Not reproducible in Chrome or Safari.
- Not reproducible on http://davidtheclark.github.io/react-aria-modal/demo
- No further issues as a result of this, the react app continues to work fine

**Comment by davidtheclark** [comment]
I'm not reproducing this error anymore with the latest library and latest Firefox, so closing.
