### ISSUE TITLE
Uncaught TypeError: Cannot read property 'componentDidUpdate' of null

### ISSUE THREAD

**Issue by moroshko** [davidtheclark/react-aria-modal#18]
Thanks a lot for a great accessible component!

I'm trying to add a demo example to [react-autosuggest](http://react-autosuggest.js.org/) that uses `react-aria-modal`. 
Unfortunately, I get the following error when closing the modal:

> Uncaught TypeError: Cannot read property 'componentDidUpdate' of null

**To reproduce:**
1. `git clone git@github.com:moroshko/react-autosuggest.git`
2. `cd react-autosuggest`
3. `git checkout 2b90102`
4. `npm install`
5. `npm start`
6. In the Full Screen example, click "Change" to open the modal
7. Click on some country to close the modal

Now you should see the error above in the console.

**Comment by davidtheclark** [comment]
@moroshko Sorry this fell through the cracks for me. The steps to reproduce no longer work so I don't have enough information here to debug. If you can provide more information or update steps, please re-open.
