### ISSUE TITLE
Disable all inline styles?

### ISSUE THREAD

**Issue by thejase** [davidtheclark/react-aria-modal#21]
I'd really love to be able to specify an `underlayClass`, and then use that to fully style the modal without needing `!important`.   Sending properties to `underlayStyle` only extends the default styles.

**Comment by davidtheclark** [comment]
> Sending properties to underlayStyle only extends the default styles.

I believe you can empty the style object by passing empty values, right?

However, I agree that you should be able to do what you want (simply disable all inline styles and add a class, without having to pass an object full of empty values). Open to a PR!

**Comment by thejase** [comment]
Thanks!  I'll look into it and send a PR!

**Comment by thejase** [comment]
Submitted in #24

**Comment by davidtheclark** [comment]
Done in #24.
