### ISSUE TITLE
onTransitionEnd?

### ISSUE THREAD

**Issue by thejase** [davidtheclark/react-aria-modal#23]
Is there any way to latch onto the underlay/dialog `onTransitionEnd` events?  I'm seeing your method of applying animation to the modal in demo five, but I'm leery to rely on setTimeout, as I'm using external CSS, and I would hate to have to edit the transition times in both places.

**Comment by davidtheclark** [comment]
@thejase I guess I don't understand the question. You can use `onTransitionEnd` if you'd like, right? Is something preventing that?

**Comment by davidtheclark** [comment]
Closing as stale. Please re-open to continue the discussion.
