### ISSUE TITLE
Support for applying custom aria- or data- attributes

### ISSUE THREAD

**Issue by ccabrales** [davidtheclark/react-aria-modal#30]
Is there any thought on adding support for custom aria or data attributes on the dialog? For example, I also want to use aria-describedby to enhance accessibility, but currently there is no way to add it.

**Comment by davidtheclark** [comment]
@ccabrales: Can you please give more details about the API you'd like — what inputs, and what rendering changes?

**Comment by ccabrales** [comment]
@davidtheclark Essentially being able to forward any aria- or data- attributes to the dialog div (the one with `aria-label` or `aria-labelledby`).

For example, if I pass `aria-describedby` as a prop to AriaModal, I would like it to add that prop to the dialog div:
```
<AriaModal
     titleText='demo seven'
     onExit={this.deactivateModal}
     getApplicationNode={this.getApplicationNode}
     includeDefaultStyles={false}
     underlayClass='demo-seven__underlay'
     dialogClass='demo-seven__dialog'
     dialogStyle={{ color: '#8a1a1a' }}
     aria-describedby='id-goes-here'
>
     {content}
</AriaLabel>
```
This would then add to `dialogProps` on line 150, similar to how `aria-labelledby` and `aria-label` are already being added. Does that make sense? Like what is addressed in another project in [this PR](https://github.com/reactjs/react-modal/pull/230/files). Let me know what you think.

**Comment by davidtheclark** [comment]
@ccabrales: Sure, sounds fine! Open to a PR.
