### ISSUE TITLE
React 15.6.x warnings

### ISSUE THREAD

**Issue by lord-xeon** [davidtheclark/react-aria-modal#35]
Upon using react v15.6.1 I get this warning message in the console:

> Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

Looks like it's a relatively easy fix

**Comment by davidtheclark** [comment]
> Looks like it's a relatively easy fix

🆒  Open to a PR!

**Comment by lord-xeon** [comment]
> 🆒 Open to a PR!

I'd love to when I get time maybe this evening, but I wanted to get it out there in case someone else had the time

**Comment by vnglst** [comment]
Maybe I could find a minute or two tomorrow to do this. Let me know if you already started on it @lord-xeon.

**Comment by davidtheclark** [comment]
Fixed by #37.
