### ISSUE TITLE
Can't navigate to browser chrome

### ISSUE THREAD

**Issue by jlous** [davidtheclark/react-aria-modal#40]
To qualify as fully accessible, it should (at least optionally) be possible to tab out into the browser chrome, as with normal pages.

This guy has some good input on accessibility and modals (although without considering react):
https://www.smashingmagazine.com/2014/09/making-modal-windows-better-for-everyone/

**Comment by davidtheclark** [comment]
Thanks! Found that point and example code in the ["Going full screen"](https://www.smashingmagazine.com/2014/09/making-modal-windows-better-for-everyone/#going-full-screen) section. Open to a PR fixing this, probably in [focus-trap](https://github.com/davidtheclark/focus-trap).

**Comment by davidtheclark** [comment]
@jlous — Curious: Have you seen any examples of accessible modals that do this (or recommendations besides that article)? Every example I come across contains focus completely within the modal.

**Comment by jlous** [comment]
No, I have not. But I was drawn to this implementation because it generally
takes usability seriously.

**Comment by jlous** [comment]
This is by no means make-or-break to my use case, and I have not yet
addressed it in the homebrew solution I ended up with. Just put it out
there in case the most accessibility-conscious modal could conquer this
point too. But i see how it would require maybe too much change. Even the
solution in the article I mentioned only works one way out of the dialog.

**Comment by davidtheclark** [comment]
I'm unable to find sufficient confirmation that this is *desirable* and *expected* behavior for a modal, so I'm going to close. If someone is able to show that more than one expert believes this is the right thing to do, please open an issue in [focus-trap](https://github.com/davidtheclark/focus-trap), the library that tries to manage focus.
