### ISSUE TITLE
Scrolling within modal

### ISSUE THREAD

**Issue by AlecRust** [davidtheclark/react-aria-modal#43]
This module prevents scroll of the page when a modal is opened with [no-scroll](https://github.com/davidtheclark/no-scroll), which is what I'm after.

However this also seems to disable scrolling of content within the modal. For example I have a 3rd party `<iframe>` inside which I can't find a way to make scrollable.

Perhaps `react-aria-modal` could only disable the scroll of the main page, but nothing else?

**Comment by davidtheclark** [comment]
@AlecRust: no-scroll disables scrolling on the document, not on the modal or the fixed-position modal's backdrop. So you can have internal scrolling within the modal or backdrop. 

I'm not sure I'm understanding the issue correctly, though — sounds like you're running into problems with an iframe, specifically, not the modal?

**Comment by AlecRust** [comment]
You're absolutely right, my apologies. I was having an [iframe scroll issue](https://davidwalsh.name/scroll-iframes-ios), nothing to do with `react-aria-modal` :)
