### ISSUE TITLE
noScroll Prop, problem with recaptcha

### ISSUE THREAD

**Issue by codingcircus** [davidtheclark/react-aria-modal#46]
I just saw, that there was already an issue for adding a prop to turn off the noscroll functionality (https://github.com/davidtheclark/react-aria-modal/issues/39), where you said you won't do this for now, however this morning I ran into a problem with the noScroll part of the modal. 

I have a modal with a form inside that uses googles invisble recaptcha. Unfortunately the position fixed and negative top you apply via no-scroll led to the captcha part (selecting pictures …) being somewhere off the screen. 

Currently I set the noScroll to off manually, but it would be nicer, if there was a way to not even turn it on in the first place. If you want I can also send a PR for a possible solution.

**Comment by davidtheclark** [comment]
I guess if adding another prop won't be a big deal if there are these necessary use cases. Please submit a PR and I'll take a look. Thanks!

**Comment by davidtheclark** [comment]
Closed by #49.
