### ISSUE TITLE
#IE-11# react aria modal seems to be reading the entire modal content when an modal element is focused 

### ISSUE THREAD

**Issue by emmazzw** [davidtheclark/react-aria-modal#54]
When we were doing the accessibility test for our react aria modal with IE 11, NVDA was reading the entire modal content out even though a modal input box was focused with mouse hovering the modal underlay part. Only by hovering back to the focused element, NVDA could stop reading other info but the focused(hovered as well) element itself. Chrome doesn't seems to have this issue..

Could someone help with a fix?

**Comment by davidtheclark** [comment]
I don't think this is a problem with this component. If anybody disagrees, though, please re-open.
