### ISSUE TITLE
Can't set returnFocusOnDeactivate on FocusTrap

### ISSUE THREAD

**Issue by cnelson9** [davidtheclark/react-aria-modal#55]
I have a scenario where I need to set returnFocusOnDeactivate to false on the FocusTrap, but there is no way for me to set it with the AriaModal props.

I would make a PR, but I don't have permission to publish a branch.

**Comment by cnelson9** [comment]
Actually, it would be nice if I could pass in all of focusTrapOptions

**Comment by davidtheclark** [comment]
@cnelson9 sounds good. Open to a PR implementing `focusTrapOptions`.

> I would make a PR, but I don't have permission to publish a branch.

You should be able to create a PR by forking the repo and working from the fork. There are some guides you can find if you search for how to contribute  pull requests on GitHub (like [this one](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github)).

**Comment by davidtheclark** [comment]
Closed by #56.
