### ISSUE TITLE
Ability to override default styles

### ISSUE THREAD

**Issue by ericedem** [davidtheclark/react-aria-modal#59]
Hey @davidtheclark, thanks for the awesome component!

Would love the ability to override individual styles like z-index. This would be nice over time so that we don't need to keep our styles up to date with `react-aria-modal`.

I'd propose an interface like:

```
<AriaModal
  ...
  overrideDialogStyle={{
    zIndex: 2
  }}
  ...
>
```

Where the `overrideDialogStyle` object would get mixed into the `dialogStyle`: https://github.com/davidtheclark/react-aria-modal/blob/72433f299d2a080538adf649ee3927e27791cf9c/src/react-aria-modal.js#L153-L160

Happy to submit a PR if this sounds reasonable.

Thanks!

**Comment by davidtheclark** [comment]
@ericedem Have you tried the `dialogStyle` and `underlayStyle` props? I believe those are supposed to do just what you're looking for.

**Comment by ericedem** [comment]
You are correct 🤦‍♂️ . `underlayStyle` fixes my problem. Thanks for the quick response!
