### ISSUE TITLE
What if there are no focusable elements within a modal?

### ISSUE THREAD

**Issue by everdimension** [davidtheclark/react-aria-modal#60]
Hi! I have just browsed at your library a little bit, so i haven't had the time to actually check this, and it's just a guess that you might want to look into.

* Scenario 1:
What if the modal has no focusable elements within? Will it still trap focus correctly?

* Scenario 2:
What if I'm dynamically changing content within a modal? E.g. I might have a multi-step form inside of it or something. And one of the steps has no focusable elements. Will the focus trap be lost when we reach this step?

**Comment by davidtheclark** [comment]
@everdimension 

1. Review existing issues to learn about this.

2. Try it out and see what happens. If you find behavior that seems buggy, please file a new issue about the bug.
