### ISSUE TITLE
Clarifying behavior wrt children when modal is not mounted

### ISSUE THREAD

**Issue by oyeanuj** [davidtheclark/react-aria-modal#64]
Hi @davidtheclark, 

I noticed that when `children` are passed to the `<AriaModal />` component, they are being accessed/rendered even when the `mounted` is false. I was a little surprised by that, and was wondering if that is by design.

If yes,
1. Do you think we should mention it in the docs in the `mounted` section so that folks are aware?
2. Thoughts on a render prop pattern where the `AriaModal` component can take a function as a child and let it know if it is `mounted` or not?

Thanks!

**Comment by davidtheclark** [comment]
:wave: @oyeanuj. 

> I noticed that when children are passed to the <AriaModal /> component, they are being accessed/rendered even when the mounted is false.

[Demo four](http://davidtheclark.github.io/react-aria-modal/demo/) shows usage of the `mounted` property working as expected: the modal is not rendered when `mouted={false}`. So I either don't understand your question or you might have a bug in your implementation?

**Comment by davidtheclark** [comment]
Closing as stale.
