### ISSUE TITLE
Switch from using react-displace to using react-portals.

### ISSUE THREAD

**Issue by Ross-Esmond** [davidtheclark/react-aria-modal#67]
Portals makes react-displace redundant. [Discussion from react-displace repo.](https://github.com/davidtheclark/react-displace/issues/6) Removing one more dependency would be nice, although it would change react compatibility from 15 to 16 and might require a breaking API change. It might make since to "shelve" this issue but leave it in the backlog for the next major version, if and when that comes.

I can help out with this one if you'd like.

**Comment by davidtheclark** [comment]
Thanks @Ross-Esmond. react-displace uses Portals when they're available and older methods when they're not. I'm not planning to remove compatibility for React 15 just yet, so still don't want to shake the react-displace dependency.
