### ISSUE TITLE
Not able to tab into iframe

### ISSUE THREAD

**Issue by mtrueblood** [davidtheclark/react-aria-modal#68]
When we put an iframe into the modal-body, we're unable to tab into the iframe.

I even went to the demo page and updated the modal-body section of demo number 5 with a random youtube iframe embed code. I'm unable to tab and click to watch the video and the focus then gets stuck on the 'deactivate modal' button. Here is a screenshot:
![image](https://user-images.githubusercontent.com/7134168/41992974-f6d1fc1e-7a17-11e8-936d-2b1a69108c6c.png)

We're having the same issue, however our close button comes before the iframe. When we tab once, we get our close button, when we tab again expecting to now be on the iframe, we're actually stuck on the close button and cannot get into the iframe.

**Comment by davidtheclark** [comment]
Yeah, this is a known issue with the lower-level tabbable library: https://github.com/davidtheclark/tabbable/issues/23. Solutions welcome!

**Comment by davidtheclark** [comment]
Closing here, as the root problem is in tabbable and focus-trap.
