### ISSUE TITLE
How to handle ESC key press for components rendered inside the modal?

### ISSUE THREAD

**Issue by jknanda78** [davidtheclark/react-aria-modal#72]
Hello,

I have a menu component that will close on ESC keypress. But while doing that the modal gets closed.

Is there a way to handle ESC keypress for components (rendered inside the modal) without closing the modal? Something out of the box?

Thanks in advance.

**Comment by davidtheclark** [comment]
Have you tried `event.stopPropagation()` on the escape event you capture for you menu?

**Comment by jknanda78** [comment]
I did try and it worked. But I thought if the solution could be available from your component.

Thanks.

**Comment by davidtheclark** [comment]
Thanks @jknanda78. I think `e.stopPropagation()` is the standard way to do this, and I don't know of anything we could do from *this* component to make it easier than that.
