### ISSUE TITLE
Using component in Typescript

### ISSUE THREAD

**Issue by amoreau2002** [davidtheclark/react-aria-modal#80]
Having issue implementing the AriaModal component in typescript.
Compiler always show me "Type '() => void' is not assignable to type '() => ReactNode'" on render method.
Any one have used it in typescript before ?

**Comment by amoreau2002** [comment]
Thx @olabaloo i have strip every part of my app and have past your DemoOne injto my app.tsx.
I still have this anoying error : 

react-dom.development.js:62 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

If you ever encounter such any help would be greatly appreciate !!

**Comment by olabaloo** [comment]
@amoreau2002 This looks like a react usage error that is unrelated to react-aria-modal. I suggest you google how to fix it.
