### ISSUE TITLE
Handling inner focus-traps

### ISSUE THREAD

**Issue by ericschultz** [davidtheclark/react-aria-modal#86]
I'm trying to wrap my head around focus-trap and modals. In particular, if you have a focus-trap inside your modal, you're supposed to set `focusTrapPaused` to true on the modal. I was considering creating a component to manage this situation but I want to make sure I understand it. Do you foresee any situation where someone WOULDN'T want to pause an outer focus-trap when an inner one is active?

**Comment by davidtheclark** [comment]
Hi @ericschultz. With the recent v4 nested focus traps should automatically pause: https://github.com/davidtheclark/react-aria-modal/blob/master/CHANGELOG.md#400. Does that solve your problem?

**Comment by ericschultz** [comment]
@davidtheclark I hadn't seen that! The [README.md](https://github.com/davidtheclark/react-aria-modal#focustrappaused) still says that you need to manually paused if you have a nested focus-trap so I assumed that was still true.

**Comment by davidtheclark** [comment]
Great, @ericschultz. I adjusted the docs in 9dd1bb05dd3f47a242db9a13ca86b4c63d2fb6f5.
