### ISSUE TITLE
Context not being passed

### ISSUE THREAD

**Issue by jamesjjk** [davidtheclark/react-aria-modal#9]
Hi, any child components to the Aria model seem to be loosing their context. It looks like its not being passed through correctly.

Thanks

**Comment by davidtheclark** [comment]
This does not surprise me, because react-displace is used to take the modal out of its expected DOM position. The modal's contents are subject to a separate `ReactDOM.render()` call. So I'm not sure there is any way to pass context through. Open to ideas!

**Comment by thomblake** [comment]
https://github.com/facebook/react/issues/4706 ?

**Comment by thomblake** [comment]
(We are also having this problem) - react-router LifeCycle does not play well with react-aria-modal right now.

**Comment by davidtheclark** [comment]
Thanks for the link. Seems like `unstable_renderSubtreeIntoContainer` is worth a try.

**Comment by thomblake** [comment]
So I don't know if it's what you want but the linked commit solves it and has a test and this solves my issue.

**Comment by davidtheclark** [comment]
Very cool, thanks! I will look into this within the next day or two, merge and release!

**Comment by davidtheclark** [comment]
@thomblake: Do you want to submit a PR to react-displace? Or do you just want me to copy code over?

**Comment by thomblake** [comment]
Sure I'll PR

**Comment by davidtheclark** [comment]
Fix published in 2.1.0. Thanks again everybody!

**Comment by thomblake** [comment]
Thanks for getting this out!

@jamesjjk ping In case you're not following this issue and it's still relevant.
